spring.application.name=nidanVitals

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:./src/main/resources/database/nidanVitals.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true